spring:
  application:
    name: mission
  datasource:
    url: jdbc:postgresql://localhost:5432/mission_db
    username: mission_user
    password: mission_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
